apiVersion: v1
kind: Secret
metadata:
  namespace: workshop
  name: mongo-sec
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= #password123 {echo password123  | base64}{echo cGFzc3dvcmQxMjM= | base64 --decode}
  username: YWRtaW4= #admin
